version: "3.7"
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: shoredb
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
