version: "3.7"

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: shoredb
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - shoredbvol:/var/lib/postgresql/data
  shorehamex:
    depends_on: postgres
    container_name: shorehamex
    image: shorehamex
    ports:
      - 8020:8020
    volumes:
      - gostatic:/go/bin/static
